### ISSUE TITLE
DXVA2動作報告

### ISSUE THREAD

**Issue by xtne6f** [DBCTRADO/TVTestVideoDecoder#1]
要望でなく動作報告+TIPSですが、こちらの環境(IntelG31,Win7pro)では `IDirectXVideoDecoderService::GetDecoderRenderTargets()` はIMC3しか返さなかったため
以下3行を弄ったところ快適に動作しました。安いチップセットでNV12を返せない環境では参考になるかもしれません。ほかに必要な情報などあれば報告します。
(「動作しました」ってだけで正しい改変かはまったく自信ないです)

```
--- a/src/DXVA2Allocator.cpp
+++ b/src/DXVA2Allocator.cpp
@@ HRESULT CDXVA2Allocator::Alloc()
                        m_lCount - 1,
-                       D3DFMT_NV12,
+                       (D3DFORMAT)MAKEFOURCC('I','M','C','3'),
                        D3DPOOL_DEFAULT,
--- a/src/Mpeg2DecoderDXVA2.cpp
+++ b/src/Mpeg2DecoderDXVA2.cpp
@@ HRESULT CMpeg2DecoderDXVA2::CreateDecoder(IDirect3DSurface9 **ppSurface, int Sur
        for (UINT i = 0; i < Count; i++) {
-               if (pFormats[i] == D3DFMT_NV12) {
+               if (pFormats[i] == (D3DFORMAT)MAKEFOURCC('I','M','C','3')) {
                        fFound = true;
@@ HRESULT CMpeg2DecoderDXVA2::CreateDecoder(IDirect3DSurface9 **ppSurface, int Sur
        VideoDesc.SampleFormat.VideoTransferFunction = DXVA2_VideoTransFunc_709;
-       VideoDesc.Format = D3DFMT_NV12;
+       VideoDesc.Format = (D3DFORMAT)MAKEFOURCC('I','M','C','3');
```

**Comment by DBCTRADO** [comment]
逆にIntel以外はIMC3に対応していないと思いますので、対応フォーマットを調べてNV12が無ければIMC3を選択する、といったことが必要になってきますね。
難しくは無いと思いますので、IMC3も対応する方向で行きます。

ちなみに、その環境では `CDXVA2Allocator::Alloc()` 内の `CreateSurface()` にNV12を指定するとエラーになりますか？

**Comment by xtne6f** [comment]
エラーにはなりません(hr==S_OK)。ただし表示は崩れます。
![createsurface](https://cloud.githubusercontent.com/assets/2673799/12972141/dec62ea2-d0e5-11e5-9fef-198805a06992.png)

**Comment by DBCTRADO** [comment]
IMC3でデコードされて、それをNV12として描画しているように見えますね。
やはりきちんと対応を判定する必要がありますね。

**Comment by DBCTRADO** [comment]
9f521813129bda7f796d9f345b234c4e08dc0e4a で、NV12に対応しておらずIMC3が利用できる場合は、IMC3を使うようにしました。

**Comment by xtne6f** [comment]
ありがとうございます、動作確認しました（納得の軽負荷）。
※DeliverFrame()のPixelCopyI420ToI420()の部分は未確認です。どうしたらパスできるか探し出せなかった…

このIssue、しばらく開けといたほうがいいでしょうか？処遇お任せします

**Comment by DBCTRADO** [comment]
その部分はDXVAでのインターレース解除のテストをしていた時のもので、今は通りませんが一応対応させておいたものです。

このIssueは対応したということで閉じますので、また何かありましたら新しく立ててください。
