### ISSUE TITLE
TVTVIDEODEC_SSSE3_SUPPORTが未定義のときのELARow_SSE2_SSSE3()の矛盾

### ISSUE THREAD

**Issue by xtne6f** [DBCTRADO/TVTestVideoDecoder#3]
TVTVIDEODEC_SSSE3_SUPPORTが未定義のとき、プリプロセッサにより`ELA_Score_SSSE3()`と`ELA_Result_SSSE3()`は消えますが、`ELARow_SSE2_SSSE3()`関数はこれらの存在を前提にしています。
stdafx.hによってTVTVIDEODEC_SSSE3_SUPPORTは実際のところ常に定義されますが、意図してSSSE3以上のSIMDを踏まないコードを生成したい場合にこの関数が矛盾します。
`Deinterlace.cpp`のL591～L593にも`#ifdef TVTVIDEODEC_SSSE3_SUPPORT`を挟んではどうでしょうか。

// 現行コードに不具合があるわけではないので、次回更新のついでにでも…

**Comment by DBCTRADO** [comment]
修正しました。

**Comment by xtne6f** [comment]
確認しました。素早い対応感謝です。
