### ISSUE TITLE
D3D11 でのデコード対応におけるインタレ解除の動作

### ISSUE THREAD

**Issue by pikesaury** [DBCTRADO/TVTestVideoDecoder#6]
D3D11 でのデコード対応ありがとうございます。UHD770でもハードウエアエンコードで映像崩れがなくなり、とても快適に使えるようになりました。感謝いたしております。

今回ご報告する内容ですが、設定をかえれば回避できるためお手すきの際にご確認いただければですが、Yafid Bob[60fps]、ELAでインターレース解除をした場合に添付のような映像崩れがおこるようです(madVR、EVR両方で発生)。Bobの60fps化では問題はおこらないようです。

Yafid Bob[60fps]では画面右側がくずれ、静止画状態になります（裏でうすく黄色だけが動いています）。
<img width="647" alt="スクリーンショット 2022-04-19 092350" src="https://user-images.githubusercontent.com/37852075/163896985-0e1d88ba-a551-431d-94d4-bfedd805b37e.png">

ELAでは画面左側がくずれるようです（薄いですが左側に青の膜のようなものがかかります）。
![99999](https://user-images.githubusercontent.com/37852075/163909627-fc5bd22e-068d-4368-ab26-994755028b16.png)

**Comment by DBCTRADO** [comment]
インターレース解除に関しては、NV12 に対応させる必要があることを失念していました。
修正します。

**Comment by pikesaury** [comment]
ありがとうございます。Yafid Bob[60fps]、ELAにて動画崩れなく表示される事を確認しました！
素早いご対応ありがとうございます！
大丈夫だと思いますが、数日様子をみてから本件CLoseさせていただきます。

**Comment by pikesaury** [comment]
![aaaaa](https://user-images.githubusercontent.com/37852075/164696647-7202e055-15e8-42cc-9597-108445612554.png)
お世話になります。再オープンさせていただきました。
添付画像のようにD3D11でインタレ解除を行うと”すじ”が入ってしまうようです。
現在はYafid Bob[60fps]をつかって再現しております。

**Comment by pikesaury** [comment]
上記の1080、1088問題は解消しましたありがとうございます。
サブチャンネル（SD画質）でD3D11＋Yafid Bob[60fps]でインタレ解除を行うと、
上の画像のように右側に空白ができてしまうようです。次々すみません。こちらもご報告させていただきます。
![11111](https://user-images.githubusercontent.com/37852075/164951776-b6e54850-19f6-4af8-b46d-5fef5f00246b.png)
![22222](https://user-images.githubusercontent.com/37852075/164951778-1cc7d638-3243-40cd-8f27-a96c32e28930.png)

**Comment by pikesaury** [comment]
上記早速のご対応大変ありがとうございました。問題が解決を致しましたのでcloseさせていただきます。この度は当方のD3D11対応のご要望から迅速にご対応いただき大変感謝いたしております。ありがとうございます。
