### ISSUE TITLE
COMPointer::IsEqualObject() を使えない

### ISSUE THREAD

**Issue by xtne6f** [DBCTRADO/TVTestVideoDecoder#7]
今のところこのメソッドは利用されていないのでコンパイラ警告だけですが、`IDD_PPV_ARGS_IUNKNOWN` が未定義になっています。利用するようなコードを試しに書いてみると、やはりエラーになります (Visual Studio Community 2022)。
この部分、`QueryInterface(IID_PPV_ARGS(&pUnk1))` とするか `QueryInterface(IID_IUnknown, reinterpret_cast<void**>(&pUnk1))` とするつもりだったのではないか？と予想します。

**Comment by DBCTRADO** [comment]
LibISDB からコードをコピペした際に漏れました。

**Comment by xtne6f** [comment]
修正確認しました。ありがとうございます。

> LibISDB からコードをコピペした際に漏れました。

たしかに。LibISDB 由来のものなのですね。
